
MAX_COMPOSITE_ADDRESSES = 5
MAX_COMPOSITE_EMAILS = 5
MAX_COMPOSITE_PHONES = 5
MAX_COMPOSITE_FACEBOOK_LINKS = 5
MAX_COMPOSITE_LINKEDIN_LINKS = 5
MAX_COMPOSITE_INSTAGRAM_LINKS = 5
MAX_COMPOSITE_TWITTER_LINKS = 5
MAX_COMPOSITE_YOUTUBE_LINKS = 5